name: CI

on:
- push
- pull_request
- workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with Python ${{ matrix.python }}
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v5
      - name: setup test environment
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: install OS packages
        run: |
          sudo apt-get upgrade
          sudo apt-get install poppler-utils mupdf-tools
      - name: install pip
        run:
          python -m pip install --upgrade pip wheel
      - name: install package
        run:
          python -m pip install .[dev]
      - name: test
        run: 
          coverage run -m unittest discover --verbose --start-directory tests/
      - name: coverage report
        run:
          coverage report
      - name: lint
        run:
          flake8
      - name: codespell
        run:
          codespell
